export const overviewData = {
  total_umkm: 10000,
  avg_score: 56.8,
  high_risk_count: 215,
  survival_rate: 67.99,
  score_distribution: [
    { range: '0-10', count: 98 },
    { range: '10-20', count: 612 },
    { range: '20-30', count: 978 },
    { range: '30-40', count: 1156 },
    { range: '40-50', count: 1089 },
    { range: '50-60', count: 1234 },
    { range: '60-70', count: 1567 },
    { range: '70-80', count: 1823 },
    { range: '80-90', count: 1043 },
    { range: '90-100', count: 400 },
  ],
  top_kabupaten: [
    { name: 'Kota Bekasi', avg_score: 85.2 },
    { name: 'Kota Depok', avg_score: 82.7 },
    { name: 'Kota Bandung', avg_score: 79.4 },
    { name: 'Kab. Bogor', avg_score: 72.1 },
    { name: 'Kota Cimahi', avg_score: 71.8 },
    { name: 'Kab. Bandung Barat', avg_score: 68.3 },
    { name: 'Kab. Bandung', avg_score: 65.4 },
    { name: 'Kab. Karawang', avg_score: 61.2 },
    { name: 'Kab. Bekasi', avg_score: 59.8 },
    { name: 'Kab. Subang', avg_score: 52.3 },
  ],
  cluster_distribution: [
    { name: 'Urban Digital Leaders', count: 2368 },
    { name: 'Rural Developing', count: 2684 },
    { name: 'Urban Digital Leaders (2)', count: 926 },
    { name: 'High-Risk Underserved', count: 2124 },
    { name: 'High-Risk Underserved (4)', count: 1898 },
  ],
};

export const creditData = {
  bands: [
    { rating: 'AAA (Excellent)', scoreRange: '750-850', count: 976, pctPortfolio: '9.8%', defaultRate: '3.9%', meanPD: '13.2%', color: '#10B981' },
    { rating: 'AA (Very Good)', scoreRange: '700-749', count: 1534, pctPortfolio: '15.3%', defaultRate: '4.2%', meanPD: '23.1%', color: '#34D399' },
    { rating: 'A (Good)', scoreRange: '650-699', count: 1691, pctPortfolio: '16.9%', defaultRate: '7.5%', meanPD: '31.8%', color: '#6EE7B7' },
    { rating: 'BBB (Adequate)', scoreRange: '600-649', count: 1549, pctPortfolio: '15.5%', defaultRate: '12.7%', meanPD: '40.8%', color: '#FCD34D' },
    { rating: 'BB (Below Average)', scoreRange: '550-599', count: 1265, pctPortfolio: '12.7%', defaultRate: '30.2%', meanPD: '49.8%', color: '#F59E0B' },
    { rating: 'B (Weak)', scoreRange: '450-549', count: 1975, pctPortfolio: '19.8%', defaultRate: '73.5%', meanPD: '63.4%', color: '#EF4444' },
    { rating: 'CCC/CC/C (Very Weak)', scoreRange: '300-449', count: 1010, pctPortfolio: '10.1%', defaultRate: '93.3%', meanPD: '79.5%', color: '#991B1B' },
  ],
  pdBuckets: [
    { bucket: '1-3%: Low risk', count: 2, pctPortfolio: '0.0%', defaultRate: '0.0%', avgPD: '2.40%', expectedLoss: '1.08%' },
    { bucket: '3-5%: Moderate risk', count: 17, pctPortfolio: '0.2%', defaultRate: '5.9%', avgPD: '4.22%', expectedLoss: '1.90%' },
    { bucket: '5-10%: Elevated risk', count: 170, pctPortfolio: '1.7%', defaultRate: '2.9%', avgPD: '7.91%', expectedLoss: '3.56%' },
    { bucket: '10-20%: High risk', count: 1054, pctPortfolio: '10.5%', defaultRate: '4.3%', avgPD: '15.76%', expectedLoss: '7.09%' },
    { bucket: '20-50%: Very high risk', count: 5173, pctPortfolio: '51.7%', defaultRate: '10.2%', avgPD: '34.59%', expectedLoss: '15.56%' },
    { bucket: '50%+: Default imminent', count: 3584, pctPortfolio: '35.8%', defaultRate: '73.2%', avgPD: '66.05%', expectedLoss: '29.72%' },
  ],
};

export const clusterData = {
  profiles: [
    { id: 0, name: 'Urban Digital Leaders', n_umkm: 2368, avg_score: 79.2, infra_score: 83.1, digital_pct: 74.1, survival_rate: 71.9, avg_omset: 76.9, income: 11.4 },
    { id: 1, name: 'Rural Developing', n_umkm: 2684, avg_score: 53.7, infra_score: 65.9, digital_pct: 41.5, survival_rate: 68.4, avg_omset: 51.4, income: 7.4 },
    { id: 2, name: 'Urban Digital Leaders (2)', n_umkm: 926, avg_score: 66.0, infra_score: 81.6, digital_pct: 64.9, survival_rate: 66.8, avg_omset: 66.2, income: 10.8 },
    { id: 3, name: 'High-Risk Underserved', n_umkm: 2124, avg_score: 31.4, infra_score: 53.1, digital_pct: 31.4, survival_rate: 65.1, avg_omset: 45.0, income: 5.5 },
    { id: 4, name: 'High-Risk Underserved (4)', n_umkm: 1898, avg_score: 54.1, infra_score: 66.9, digital_pct: 51.9, survival_rate: 66.4, avg_omset: 57.1, income: 7.8 },
  ],
  govPriority: [
    { rank: 1, cluster: 'High-Risk Underserved', n_umkm: 2124, priority_score: 0.968, budget_pct: 41.5 },
    { rank: 2, cluster: 'High-Risk Underserved (4)', n_umkm: 1898, priority_score: 0.725, budget_pct: 27.8 },
    { rank: 3, cluster: 'Rural Developing', n_umkm: 2684, priority_score: 0.484, budget_pct: 26.2 },
    { rank: 4, cluster: 'Urban Digital Leaders (2)', n_umkm: 926, priority_score: 0.191, budget_pct: 3.6 },
    { rank: 5, cluster: 'Urban Digital Leaders', n_umkm: 2368, priority_score: 0.019, budget_pct: 0.9 },
  ],
  investment: [
    { rank: 1, cluster: 'Urban Digital Leaders', n_umkm: 2368, investment_score: 0.962, market_size_juta: 182167 },
    { rank: 2, cluster: 'Rural Developing', n_umkm: 2684, investment_score: 0.525, market_size_juta: 137994 },
    { rank: 3, cluster: 'Urban Digital Leaders (2)', n_umkm: 926, investment_score: 0.522, market_size_juta: 61278 },
    { rank: 4, cluster: 'High-Risk Underserved (4)', n_umkm: 1898, investment_score: 0.489, market_size_juta: 108319 },
    { rank: 5, cluster: 'High-Risk Underserved', n_umkm: 2124, investment_score: 0.200, market_size_juta: 95654 },
  ],
};

export const policyData = {
  impacts: [
    { policy: 'KUR Expansion (+20%)', target: 'Low-KUR areas (3,041 UMKMs)', avgImprovement: 0.88, pctImproved: 93.9, newAbove70: 14, additionalSurvivors: 23 },
    { policy: 'Infrastructure +30', target: 'Low-infra areas (2,507 UMKMs)', avgImprovement: 19.87, pctImproved: 100.0, newAbove70: 244, additionalSurvivors: 88 },
    { policy: 'Digital Training (50%)', target: 'Non-digital UMKMs (2,439 trained)', avgImprovement: 9.63, pctImproved: 100.0, newAbove70: 325, additionalSurvivors: 58 },
  ],
  priorityKecamatan: [
    { kecamatan: 'Sagaranten', kabupaten: 'Kab. Sukabumi', avg_skor: 1.36, rank: 1, factor: 'digital_readiness', recommendation: 'Prioritas: Program pelatihan digital dan perluasan internet' },
    { kecamatan: 'Cisompet', kabupaten: 'Kab. Garut', avg_skor: 6.82, rank: 2, factor: 'digital_readiness', recommendation: 'Prioritas: Program pelatihan digital dan perluasan internet' },
    { kecamatan: 'Cihurip', kabupaten: 'Kab. Garut', avg_skor: 7.21, rank: 3, factor: 'digital_readiness', recommendation: 'Prioritas: Program pelatihan digital dan perluasan internet' },
    { kecamatan: 'Cidolog', kabupaten: 'Kab. Ciamis', avg_skor: 7.49, rank: 4, factor: 'digital_readiness', recommendation: 'Prioritas: Program pelatihan digital dan perluasan internet' },
    { kecamatan: 'Hantara', kabupaten: 'Kab. Kuningan', avg_skor: 8.21, rank: 5, factor: 'infrastructure', recommendation: 'Prioritas: Pembangunan infrastruktur jalan dan pasar' },
    { kecamatan: 'Langkaplancar', kabupaten: 'Kab. Pangandaran', avg_skor: 10.7, rank: 6, factor: 'digital_readiness', recommendation: 'Prioritas: Program pelatihan digital dan perluasan internet' },
    { kecamatan: 'Cicurug', kabupaten: 'Kab. Sukabumi', avg_skor: 11.32, rank: 7, factor: 'digital_readiness', recommendation: 'Prioritas: Program pelatihan digital dan perluasan internet' },
    { kecamatan: 'Cidahu', kabupaten: 'Kab. Sukabumi', avg_skor: 11.45, rank: 8, factor: 'digital_readiness', recommendation: 'Prioritas: Program pelatihan digital dan perluasan internet' },
    { kecamatan: 'Singajaya', kabupaten: 'Kab. Garut', avg_skor: 11.59, rank: 9, factor: 'infrastructure', recommendation: 'Prioritas: Pembangunan infrastruktur jalan dan pasar' },
    { kecamatan: 'Kertajati', kabupaten: 'Kab. Majalengka', avg_skor: 12.64, rank: 10, factor: 'financial_access', recommendation: 'Prioritas: Ekspansi layanan perbankan dan KUR' },
    { kecamatan: 'Bantarkalong', kabupaten: 'Kab. Tasikmalaya', avg_skor: 12.97, rank: 11, factor: 'financial_access', recommendation: 'Prioritas: Ekspansi layanan perbankan dan KUR' },
    { kecamatan: 'Culamega', kabupaten: 'Kab. Tasikmalaya', avg_skor: 13.21, rank: 12, factor: 'infrastructure', recommendation: 'Prioritas: Pembangunan infrastruktur jalan dan pasar' },
    { kecamatan: 'Garawangi', kabupaten: 'Kab. Kuningan', avg_skor: 13.32, rank: 13, factor: 'digital_readiness', recommendation: 'Prioritas: Program pelatihan digital dan perluasan internet' },
    { kecamatan: 'Peundeuy', kabupaten: 'Kab. Garut', avg_skor: 13.88, rank: 14, factor: 'digital_readiness', recommendation: 'Prioritas: Program pelatihan digital dan perluasan internet' },
    { kecamatan: 'Gegerbitung', kabupaten: 'Kab. Sukabumi', avg_skor: 14.2, rank: 15, factor: 'infrastructure', recommendation: 'Prioritas: Pembangunan infrastruktur jalan dan pasar' },
  ],
  whatifScenarios: [
    { scenario: 'Infrastructure +20% in Garut', affected: 449, before: 31.63, after: 49.38, improvement: 17.75, max_improvement: 29.21, pct_improved: 100.0, above_70: 6 },
    { scenario: 'New bank branch in Pangandaran (-50% distance)', affected: 94, before: 28.91, after: 29.15, improvement: 0.23, max_improvement: 0.51, pct_improved: 93.6, above_70: 0 },
    { scenario: 'Internet coverage 80% in Ciamis', affected: 271, before: 32.88, after: 39.55, improvement: 6.66, max_improvement: 13.64, pct_improved: 97.4, above_70: 0 },
  ],
};

export const recommendData = [
  { kabupaten: 'Kota Bekasi', kecamatan: 'Pondok Gede', jenis_usaha: 'Makanan', avg_score: 94.85, rank: 1, explanation: 'High survival (100%); Good infrastructure; Good internet' },
  { kabupaten: 'Kota Bekasi', kecamatan: 'Bekasi Selatan', jenis_usaha: 'Makanan', avg_score: 92.0, rank: 2, explanation: 'High survival (83%); Good infrastructure; Good internet' },
  { kabupaten: 'Kota Depok', kecamatan: 'Cilodong', jenis_usaha: 'Makanan', avg_score: 90.3, rank: 3, explanation: 'High survival (81%); Good infrastructure; Good internet' },
  { kabupaten: 'Kota Bandung', kecamatan: 'Rancasari', jenis_usaha: 'Makanan', avg_score: 87.6, rank: 4, explanation: 'Good infrastructure; Good internet' },
  { kabupaten: 'Kota Bandung', kecamatan: 'Astana Anyar', jenis_usaha: 'Makanan', avg_score: 90.6, rank: 5, explanation: 'High survival (88%); Good infrastructure; Good internet' },
  { kabupaten: 'Kota Bandung', kecamatan: 'Rancasari', jenis_usaha: 'Fashion', avg_score: 88.4, rank: 1, explanation: 'High survival (100%); Good infrastructure; Good internet' },
  { kabupaten: 'Kota Bekasi', kecamatan: 'Pondok Gede', jenis_usaha: 'Fashion', avg_score: 91.1, rank: 2, explanation: 'High survival (80%); Good infrastructure; Good internet' },
  { kabupaten: 'Kota Depok', kecamatan: 'Sukmajaya', jenis_usaha: 'Fashion', avg_score: 77.2, rank: 3, explanation: 'Good infrastructure; Good internet' },
  { kabupaten: 'Kota Bandung', kecamatan: 'Coblong', jenis_usaha: 'Kerajinan', avg_score: 78.4, rank: 1, explanation: 'Good infrastructure; Good internet; Creative hub area' },
  { kabupaten: 'Kota Bekasi', kecamatan: 'Pondok Gede', jenis_usaha: 'Jasa', avg_score: 89.2, rank: 1, explanation: 'High survival; Good infrastructure; Good internet' },
  { kabupaten: 'Kota Depok', kecamatan: 'Cilodong', jenis_usaha: 'Pertanian', avg_score: 72.5, rank: 1, explanation: 'Good land access; Good infrastructure' },
];

export const kecamatanMapData = [
  { kecamatan: 'Cileunyi', kabupaten: 'Kab. Bandung', lat: -7.000, lng: 107.662, score: 62.99 },
  { kecamatan: 'Cimenyan', kabupaten: 'Kab. Bandung', lat: -6.943, lng: 107.606, score: 68.53 },
  { kecamatan: 'Cilengkrang', kabupaten: 'Kab. Bandung', lat: -7.035, lng: 107.535, score: 46.36 },
  { kecamatan: 'Bojongsoang', kabupaten: 'Kab. Bandung', lat: -7.051, lng: 107.649, score: 55.40 },
  { kecamatan: 'Margahayu', kabupaten: 'Kab. Bandung', lat: -6.964, lng: 107.623, score: 62.99 },
  { kecamatan: 'Coblong', kabupaten: 'Kota Bandung', lat: -6.893, lng: 107.616, score: 78.4 },
  { kecamatan: 'Sukajadi', kabupaten: 'Kota Bandung', lat: -6.882, lng: 107.596, score: 73.98 },
  { kecamatan: 'Rancasari', kabupaten: 'Kota Bandung', lat: -6.957, lng: 107.662, score: 87.59 },
  { kecamatan: 'Astana Anyar', kabupaten: 'Kota Bandung', lat: -6.928, lng: 107.601, score: 90.62 },
  { kecamatan: 'Pondok Gede', kabupaten: 'Kota Bekasi', lat: -6.473, lng: 106.911, score: 94.85 },
  { kecamatan: 'Bekasi Selatan', kabupaten: 'Kota Bekasi', lat: -6.267, lng: 106.994, score: 92.0 },
  { kecamatan: 'Cilodong', kabupaten: 'Kota Depok', lat: -6.418, lng: 106.849, score: 90.3 },
  { kecamatan: 'Sukmajaya', kabupaten: 'Kota Depok', lat: -6.383, lng: 106.843, score: 81.3 },
  { kecamatan: 'Bojonggede', kabupaten: 'Kab. Bogor', lat: -6.507, lng: 106.797, score: 81.47 },
  { kecamatan: 'Sagaranten', kabupaten: 'Kab. Sukabumi', lat: -7.177, lng: 106.735, score: 1.36 },
  { kecamatan: 'Cisompet', kabupaten: 'Kab. Garut', lat: -7.424, lng: 107.815, score: 6.82 },
  { kecamatan: 'Cimahi Tengah', kabupaten: 'Kota Cimahi', lat: -6.887, lng: 107.543, score: 83.74 },
  { kecamatan: 'Pangalengan', kabupaten: 'Kab. Bandung', lat: -6.962, lng: 107.532, score: 72.5 },
  { kecamatan: 'Ibun', kabupaten: 'Kab. Bandung', lat: -7.028, lng: 107.592, score: 70.0 },
  { kecamatan: 'Cipongkor', kabupaten: 'Kab. Bandung Barat', lat: -6.850, lng: 107.415, score: 75.03 },
];

// Multi-dimensional kecamatan data for comparison radar chart
export const kecamatanDetailData = [
  { kecamatan: 'Pondok Gede', kabupaten: 'Kota Bekasi', infrastructure: 92, risk: 15, competition: 78, digital_readiness: 88, financial_access: 85 },
  { kecamatan: 'Bekasi Selatan', kabupaten: 'Kota Bekasi', infrastructure: 89, risk: 18, competition: 72, digital_readiness: 85, financial_access: 82 },
  { kecamatan: 'Cilodong', kabupaten: 'Kota Depok', infrastructure: 87, risk: 20, competition: 65, digital_readiness: 82, financial_access: 80 },
  { kecamatan: 'Rancasari', kabupaten: 'Kota Bandung', infrastructure: 85, risk: 22, competition: 70, digital_readiness: 80, financial_access: 78 },
  { kecamatan: 'Astana Anyar', kabupaten: 'Kota Bandung', infrastructure: 88, risk: 16, competition: 82, digital_readiness: 84, financial_access: 81 },
  { kecamatan: 'Coblong', kabupaten: 'Kota Bandung', infrastructure: 83, risk: 25, competition: 75, digital_readiness: 79, financial_access: 76 },
  { kecamatan: 'Sukmajaya', kabupaten: 'Kota Depok', infrastructure: 81, risk: 28, competition: 68, digital_readiness: 77, financial_access: 74 },
  { kecamatan: 'Cimahi Tengah', kabupaten: 'Kota Cimahi', infrastructure: 80, risk: 30, competition: 60, digital_readiness: 75, financial_access: 72 },
  { kecamatan: 'Bojonggede', kabupaten: 'Kab. Bogor', infrastructure: 76, risk: 35, competition: 55, digital_readiness: 68, financial_access: 65 },
  { kecamatan: 'Pangalengan', kabupaten: 'Kab. Bandung', infrastructure: 65, risk: 45, competition: 35, digital_readiness: 52, financial_access: 55 },
  { kecamatan: 'Cipongkor', kabupaten: 'Kab. Bandung Barat', infrastructure: 68, risk: 42, competition: 40, digital_readiness: 55, financial_access: 58 },
  { kecamatan: 'Sagaranten', kabupaten: 'Kab. Sukabumi', infrastructure: 32, risk: 82, competition: 15, digital_readiness: 18, financial_access: 22 },
  { kecamatan: 'Cisompet', kabupaten: 'Kab. Garut', infrastructure: 38, risk: 75, competition: 20, digital_readiness: 25, financial_access: 28 },
];

// Feature importance for SHAP-like explanations
export const featureImportanceData = {
  locationScoring: [
    { feature: 'Infrastructure x Income', importance: 0.2497, fullName: 'infra_x_income' },
    { feature: 'Internet Access %', importance: 0.2315, fullName: 'akses_internet_pct' },
    { feature: 'Location Advantage', importance: 0.1721, fullName: 'location_advantage' },
    { feature: 'Infrastructure Score', importance: 0.1238, fullName: 'skor_infrastruktur' },
    { feature: 'Income per Capita', importance: 0.1081, fullName: 'income_per_kapita' },
    { feature: 'Digital Readiness', importance: 0.0213, fullName: 'digital_readiness_index' },
    { feature: 'KUR Penetration', importance: 0.0208, fullName: 'penetrasi_kur_pct' },
    { feature: 'Digital Presence', importance: 0.0172, fullName: 'has_digital_presence' },
    { feature: 'Competitor Count', importance: 0.0154, fullName: 'jumlah_kompetitor_radius_3km' },
    { feature: 'Competition Density', importance: 0.0074, fullName: 'competition_density_ratio' },
  ],
  creditRisk: [
    { feature: 'Monthly Revenue', importance: 858, fullName: 'omset_bulanan' },
    { feature: 'Revenue per Employee', importance: 808, fullName: 'omset_per_karyawan' },
    { feature: 'Business Age', importance: 362, fullName: 'tahun_berdiri' },
    { feature: 'Digital Readiness', importance: 300, fullName: 'digital_readiness_index' },
    { feature: 'KUR Penetration', importance: 285, fullName: 'penetrasi_kur_pct' },
    { feature: 'Road Distance', importance: 271, fullName: 'jarak_ke_jalan_utama' },
    { feature: 'Risk Composite', importance: 257, fullName: 'risk_composite' },
    { feature: 'Market Gap Score', importance: 235, fullName: 'market_gap_score' },
    { feature: 'Employee Count', importance: 229, fullName: 'jumlah_karyawan' },
    { feature: 'Infrastructure Score', importance: 229, fullName: 'skor_infrastruktur' },
  ],
};

// SHAP-like explanations for each credit band (pre-computed approximate contributions)
export const shapExplanations: Record<string, { feature: string; contribution: number }[]> = {
  'AAA (Excellent)': [
    { feature: 'Monthly Revenue', contribution: 0.28 },
    { feature: 'Business Age', contribution: 0.22 },
    { feature: 'Digital Readiness', contribution: 0.18 },
    { feature: 'Revenue per Employee', contribution: 0.15 },
    { feature: 'Infrastructure Score', contribution: 0.10 },
    { feature: 'KUR Penetration', contribution: 0.05 },
    { feature: 'Road Distance', contribution: -0.02 },
    { feature: 'Competition Density', contribution: -0.05 },
  ],
  'AA (Very Good)': [
    { feature: 'Monthly Revenue', contribution: 0.22 },
    { feature: 'Business Age', contribution: 0.18 },
    { feature: 'Revenue per Employee', contribution: 0.14 },
    { feature: 'Digital Readiness', contribution: 0.12 },
    { feature: 'Infrastructure Score', contribution: 0.08 },
    { feature: 'KUR Penetration', contribution: 0.04 },
    { feature: 'Road Distance', contribution: -0.04 },
    { feature: 'Risk Composite', contribution: -0.06 },
  ],
  'A (Good)': [
    { feature: 'Monthly Revenue', contribution: 0.18 },
    { feature: 'Business Age', contribution: 0.14 },
    { feature: 'Revenue per Employee', contribution: 0.10 },
    { feature: 'Digital Readiness', contribution: 0.08 },
    { feature: 'Infrastructure Score', contribution: 0.05 },
    { feature: 'Road Distance', contribution: -0.06 },
    { feature: 'Risk Composite', contribution: -0.08 },
    { feature: 'Market Gap Score', contribution: -0.03 },
  ],
  'BBB (Adequate)': [
    { feature: 'Monthly Revenue', contribution: 0.10 },
    { feature: 'Business Age', contribution: 0.06 },
    { feature: 'Revenue per Employee', contribution: 0.04 },
    { feature: 'Road Distance', contribution: -0.08 },
    { feature: 'Risk Composite', contribution: -0.12 },
    { feature: 'Digital Readiness', contribution: -0.05 },
    { feature: 'Infrastructure Score', contribution: -0.03 },
    { feature: 'Competition Density', contribution: -0.04 },
  ],
  'BB (Below Average)': [
    { feature: 'Monthly Revenue', contribution: 0.05 },
    { feature: 'Business Age', contribution: -0.04 },
    { feature: 'Road Distance', contribution: -0.12 },
    { feature: 'Risk Composite', contribution: -0.18 },
    { feature: 'Digital Readiness', contribution: -0.10 },
    { feature: 'Infrastructure Score', contribution: -0.08 },
    { feature: 'Revenue per Employee', contribution: -0.05 },
    { feature: 'KUR Penetration', contribution: -0.06 },
  ],
  'B (Weak)': [
    { feature: 'Risk Composite', contribution: -0.25 },
    { feature: 'Road Distance', contribution: -0.18 },
    { feature: 'Digital Readiness', contribution: -0.15 },
    { feature: 'Infrastructure Score', contribution: -0.12 },
    { feature: 'Monthly Revenue', contribution: -0.08 },
    { feature: 'Revenue per Employee', contribution: -0.10 },
    { feature: 'Business Age', contribution: -0.06 },
    { feature: 'Market Gap Score', contribution: 0.03 },
  ],
  'CCC/CC/C (Very Weak)': [
    { feature: 'Risk Composite', contribution: -0.32 },
    { feature: 'Road Distance', contribution: -0.22 },
    { feature: 'Digital Readiness', contribution: -0.20 },
    { feature: 'Infrastructure Score', contribution: -0.18 },
    { feature: 'Monthly Revenue', contribution: -0.15 },
    { feature: 'Business Age', contribution: -0.12 },
    { feature: 'Revenue per Employee', contribution: -0.10 },
    { feature: 'KUR Penetration', contribution: -0.08 },
  ],
};
